/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class LibraryTest {

    private Library lib;

    @BeforeEach
    void setup() {
        lib = new Library();
    }

    // a simple all-in-one test
    // with tested method name in its name
    @Test
    void testIsEven() {
        boolean computed1 = lib.isEven(0);
        boolean expected1 = true;
        boolean computed2 = lib.isEven(1);
        boolean expected2 = false;
        boolean computed3 = lib.isEven(2);
        boolean expected3 = true;
        boolean computed2b = lib.isEven(-1);
        boolean expected2b = false;
        boolean computed3b = lib.isEven(-2);
        boolean expected3b = true;
        assertEquals(expected1, computed1);
        assertEquals(expected2, computed2);
        assertEquals(expected3, computed3);
        assertEquals(expected2b, computed2b);
        assertEquals(expected3b, computed3b);
    }

    // a simple all-in-one test
    // with a loop for testing multiple values
    @Test
    void testAdd() {
        int[][] inputs = new int[][]{
            {0, 0, 0},
            {0, 1, 1},
            {2, 0, 2},
            {3, 4, 7},
            {2, -2, 0},
            {-3, 3, 0},
            {2, -3, -1},
            {-3, 2, -1},
            {4, -3, 1},
            {-3, 4, 1}
        };
        for (int i = 0; i < inputs.length; i++) {
            int input1 = inputs[i][0];
            int input2 = inputs[i][1];
            int expected = inputs[i][2];
            int computed = lib.add(input1, input2);
            assertEquals(expected, computed);
        }
    }
}
