/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

public class Library {
    public boolean isEven(int n) {
        return n % 2 == 0;
    }

    public int add(int a, int b) {
        return a + b;
    }

    public int mul(int a, int b) {
        return a * b;
    }

    // this is an incorrect implementation
    // not detected by the tests
    public int sum(List<Integer> numbers) {
        int rtr = 0;
        if (numbers != null) {
            for (int i = 0; i < numbers.size(); i++) {
                rtr += numbers.get(i);
            }
        }
        return rtr;
    }

}
