/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Library {
    public boolean isEven(int n) {
        return n % 2 == 0;
    }

    public int add(int a, int b) {
        return a + b;
    }

    public int mul(int a, int b) {
        return a * b;
    }

}
